// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtQy3NXZNZqn-lu_sOKXl5yDFsHaIZ04c',
    appId: '1:961677687907:web:631ca3f41eff19ab328c56',
    messagingSenderId: '961677687907',
    projectId: 'genhousedb',
    authDomain: 'genhousedb.firebaseapp.com',
    databaseURL: 'https://genhousedb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'genhousedb.appspot.com',
    measurementId: 'G-L3VV11NF04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOjYbqOPx6VgIsvjK-cNiXcQArjnEVBvg',
    appId: '1:961677687907:android:128ed945e2783f78328c56',
    messagingSenderId: '961677687907',
    projectId: 'genhousedb',
    databaseURL: 'https://genhousedb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'genhousedb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbXjZ5W93v11P-fYHlmG8TsF1hbVUtesk',
    appId: '1:961677687907:ios:676381cea42098d5328c56',
    messagingSenderId: '961677687907',
    projectId: 'genhousedb',
    databaseURL: 'https://genhousedb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'genhousedb.appspot.com',
    iosBundleId: 'com.example.genHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbXjZ5W93v11P-fYHlmG8TsF1hbVUtesk',
    appId: '1:961677687907:ios:e4d46600e2f6ab47328c56',
    messagingSenderId: '961677687907',
    projectId: 'genhousedb',
    databaseURL: 'https://genhousedb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'genhousedb.appspot.com',
    iosBundleId: 'com.example.genHouse.RunnerTests',
  );
}
